// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPJyzf4kyxaOeAoLDHfqc1PgFwAsj1AAA',
    appId: '1:391055536764:web:aadb5e55cd1cf3d77ecff9',
    messagingSenderId: '391055536764',
    projectId: 'fungibite-aplikasi',
    authDomain: 'fungibite-aplikasi.firebaseapp.com',
    storageBucket: 'fungibite-aplikasi.firebasestorage.app',
    measurementId: 'G-9P8GF03NS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApXjp3BSyh4bNDpC_Me6oCrwTM4fzqZks',
    appId: '1:391055536764:android:01a0df94a80d089a7ecff9',
    messagingSenderId: '391055536764',
    projectId: 'fungibite-aplikasi',
    storageBucket: 'fungibite-aplikasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKsX5-wUOwr3VuHqeamKBeofHV00otY4E',
    appId: '1:391055536764:ios:ec9b24c1d3b4f0827ecff9',
    messagingSenderId: '391055536764',
    projectId: 'fungibite-aplikasi',
    storageBucket: 'fungibite-aplikasi.firebasestorage.app',
    iosBundleId: 'com.example.adminFungi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKsX5-wUOwr3VuHqeamKBeofHV00otY4E',
    appId: '1:391055536764:ios:ec9b24c1d3b4f0827ecff9',
    messagingSenderId: '391055536764',
    projectId: 'fungibite-aplikasi',
    storageBucket: 'fungibite-aplikasi.firebasestorage.app',
    iosBundleId: 'com.example.adminFungi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPJyzf4kyxaOeAoLDHfqc1PgFwAsj1AAA',
    appId: '1:391055536764:web:851402b8d97f34427ecff9',
    messagingSenderId: '391055536764',
    projectId: 'fungibite-aplikasi',
    authDomain: 'fungibite-aplikasi.firebaseapp.com',
    storageBucket: 'fungibite-aplikasi.firebasestorage.app',
    measurementId: 'G-34GHPDKF39',
  );
}
